language: python
install:
  - pip install -r requirements.txt
  - pip install ./
script:
  - coverage run --include=audiotools/* -m pytest -ra
after_success:
  - bash <(curl -s https://codecov.io/bash)
